<?php
/**
 * Title: Events - Call To Action Banner
 * Slug: events-directory/cta-banner
 * Categories: blockstrap-page-content
 * Viewport Width: 1280
 */


$img_url = esc_url( get_theme_file_uri( 'assets/images/demo/dining-table.jpg' ) ); /* <?php echo esc_attr( $img_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"bg":"transparent","bg_gradient":"linear-gradient(135deg,rgb(30,23,126) 4%,rgb(96,41,182) 100%)","mb_lg":"","position":"position-relative","anchor":"Lead capture","content":"","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='transparent'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgb(30,23,126) 4%,rgb(96,41,182) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor='Lead capture'  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container bg-transparent bg-image-fixed container position-relative" id="Lead capture"><!-- wp:blockstrap/blockstrap-widget-container {"bg":"purple","mb_lg":"7","border":"0","rounded_size":"1","overflow":"overflow-hidden","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='purple'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='7'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='1'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
	<div class="wp-block-blockstrap-blockstrap-widget-container mb-7 border-0 rounded-1 bg-purple bg-image-fixed container overflow-hidden"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","mb_lg":"","flex_align_items_lg":"align-items-lg-center","flex_justify_content_lg":"justify-content-lg-center","sd_shortcode":"[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"align-items-center"} -->
		<div class="wp-block-blockstrap-blockstrap-widget-container bg-image-fixed row align-items-center justify-content-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"7","bg_gradient":"linear-gradient(90deg,rgb(0,252,13) 5%,rgb(155,81,224) 100%)","bg_on_text":true,"mb_lg":"","pt_lg":"5","pr_lg":"5","pb_lg":"5","pl_lg":"5","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='7'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(90deg,rgb(0,252,13) 5%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='true'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='5'  pb_lg='5'  pl_lg='5'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
			<div class="wp-block-blockstrap-blockstrap-widget-container pt-5 pe-5 pb-5 ps-5 col-12 col-lg-7 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Ready to build your perfect community?","html_tag":"h2","text_color":"white","font_size":"h2","font_size_custom":5,"font_weight":"font-weight-bold","bg_gradient":"linear-gradient(139deg,rgb(18,255,1) 4%,rgb(175,236,241) 57%)","bg_on_text":true,"mb_lg":"","content":""} -->
				<h2 class="wp-block-blockstrap-blockstrap-widget-heading text-white font-weight-bold h2">Ready to build your perfect community?</h2>
				<!-- /wp:blockstrap/blockstrap-widget-heading -->

				<!-- wp:blockstrap/blockstrap-widget-heading {"text":"We’ll guide you through each step. Our community team is dedicated to helping you connect with your customers in real life around the world.\n\n","html_tag":"p","text_color":"white","font_size":"0","font_size_custom":5,"bg_gradient":"linear-gradient(139deg,rgb(18,255,1) 4%,rgb(175,236,241) 57%)","bg_on_text":true,"mb_lg":"0","content":""} -->
				<p class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-white">We’ll guide you through each step. Our community team is dedicated to helping you connect with your customers in real life around the world.

				</p>
				<!-- /wp:blockstrap/blockstrap-widget-heading -->

				<!-- wp:blockstrap/blockstrap-widget-button {"type":"add_gd_event","text":"Add Your Events","link_size":"large","font_weight":"font-weight-bold","mt_lg":"4","border":"0","rounded_size":"pill","styleid":"block-yve8lwgw9f","content":"\u003ca   class=\u0022btn btn-primary btn-lg mt-4 border-0 rounded-pill fw-bold block-yve8lwgw9f\u0022\u003eAdd Your Events\u003c/a\u003e ","sd_shortcode":"[bs_button type='add_gd_event'  page_id=''  meta_key=''  post_id=''  custom_url=''  text='Add Your Events'  icon_class=''  icon_position=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type='btn'  link_size='large'  link_bg='primary'  link_bg_color='#0073aa'  link_bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color=''  text_color_custom=''  bg_hover=''  bg_hover_color='#0073aa'  bg_hover_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color_hover=''  text_color_hover_custom=''  font_size_custom=''  font_weight='font-weight-bold'  font_case=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='4'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  rounded=''  rounded_size='pill'  shadow=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class=''  styleid='block-yve8lwgw9f' ]"} /--></div>
			<!-- /wp:blockstrap/blockstrap-widget-container -->

			<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"5","bg_gradient":"linear-gradient(90deg,rgb(0,252,13) 5%,rgb(155,81,224) 100%)","bg_on_text":true,"mb_lg":"","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='5'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(90deg,rgb(0,252,13) 5%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='true'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
			<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-0 pb-0 ps-0 col-12 col-lg-5 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-image {"img_src":"url","img_url":"<?php echo esc_attr( $img_url ); ?>","fallback_img_src":"default","img_alt":"Man in black suit standing on stage","img_aspect":"4by3","img_border":"0","img_rounded_size":"0","mb_lg":"0","content": "","sd_shortcode":"[bs_image img_src='url'  img_image=''  img_image_id=''  img_size=''  img_url='<?php echo esc_attr( $img_url ); ?>'  fallback_img_src='default'  fallback_img_image=''  fallback_img_image_id=''  img_alt='Man in black suit standing on stage'  img_lazyload=''  img_link_to=''  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect='4by3'  img_cover=''  img_border='0'  img_rounded=''  img_rounded_size='0'  img_shadow=''  img_overlay=''  text_color=''  font_size=''  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='0'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask=''  img_mask_position='center center'  visibility_conditions=''  css_class='' ]"} /--></div>
			<!-- /wp:blockstrap/blockstrap-widget-container --></div>
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->
