<?php
/**
 * Title: Events - Default Hero Page
 * Slug: events-directory/hero-page-default
 * Categories: blockstrap-hero-sections
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"#2e0761","bg_image":"http://localhost/wp-content/themes/events-directory/assets/images/section-bg-3.png","bg_image_id":5265,"pr_lg":"4","pl_lg":"4","border":"0","rounded_size":"0","position":"position-relative","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='#2e0761'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image='http://localhost/wp-content/themes/events-directory/assets/images/section-bg-3.png'  bg_image_id='5265'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='4'  pb_lg=''  pl_lg='4'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 pe-4 ps-4 border-0 rounded-0 bg-custom-color bg-image-fixed container-fluid position-relative" style="background-color:#2e0761;background-image:url(http://localhost/wp-content/themes/events-directory/assets/images/section-bg-3.png);background-blend-mode:overlay;background-size:cover"><!-- wp:blockstrap/blockstrap-widget-shape-divider {"sd":"tilt","sd_position":"bottom","sd_color":"white","styleid":"block-qjdp5ld5gd"} -->
	<div class="wp-block-blockstrap-blockstrap-widget-shape-divider block-qjdp5ld5gd blockstrap-shape blockstrap-shape-bottom position-absolute"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none">	<path class="bg-white blockstrap-shape-fill" d="M0,6V0h1000v100L0,6z"/></svg></div><style>.block-qjdp5ld5gd { pointer-events: none;background-repeat: no-repeat;bottom:  -1px; left: -1px;right: -1px;line-height: 0;overflow: hidden;margin: 0 1px;-webkit-transform: rotate(180deg); transform: rotate(180deg);}.block-qjdp5ld5gd svg{ height: 100px;width: calc(200% + 1.3px);left: 50%;position: relative;display: block;-webkit-transform: translateX(-50%); -ms-transform: translateX(-50%); transform: translateX(-50%);}.block-qjdp5ld5gd svg path{ }</style>
	<!-- /wp:blockstrap/blockstrap-widget-shape-divider -->

	<!-- wp:blockstrap/blockstrap-widget-container {"container":"row","bg_color":"rgba(0,117,171,0.96)","bg_image_xy":{"x":0.47,"y":0.45},"mb_lg":"","pt_lg":"4","pr_lg":"5","pb_lg":"7","pl_lg":"5","border":"0","rounded":"rounded","className":"block-1618467995"} -->
	<div class="wp-block-blockstrap-blockstrap-widget-container pt-4 pe-5 pb-7 ps-5 border-0 bg-image-fixed row rounded"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":"","className":"block-1618467995"} -->
		<div class="wp-block-blockstrap-blockstrap-widget-container bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-post-title {"text_color":"white","font_weight":"font-weight-bold","text_align_lg":"text-lg-center","mb_lg":"0"} /--></div>
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->
