<?php
/**
 * Title: Events - Hero Home
 * Slug: events-directory/hero-home-default
 * Categories: blockstrap-hero-sections
 * Viewport Width: 1280
 */

$img_url = esc_url( get_theme_file_uri( 'assets/images/demo/man-standing-stage.jpg' ) ); /* <?php echo esc_attr( $img_url ); ?> */
$txt_explore = __( 'Explore Events &amp; Secure Your Tickets', 'events-directory' ); /* <?php echo esc_attr( $txt_explore ); ?> */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"purple","bg_color":"#fef7f9","bg_gradient":"linear-gradient(90deg,rgba(0,0,0,0.73) 4%,rgba(121,33,12,0.86) 100%)","bg_image_xy":{"x":0.75,"y":0.99},"text_color":"white","mb_lg":"","position":"position-relative","content":"","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='purple'  bg_color='#fef7f9'  bg_gradient='linear-gradient(90deg,rgba(0,0,0,0.73) 4%,rgba(121,33,12,0.86) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container bg-purple bg-image-fixed text-white container-fluid position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"bg":"custom-color","bg_color":"#3d0982","mb_lg":"","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","shadow":"shadow","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='#3d0982'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow='shadow'  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
	<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-0 pb-0 ps-0 bg-custom-color bg-image-fixed container shadow" style="background-color:#3d0982"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","mb_lg":"","flex_align_items_lg":"align-items-lg-center","sd_shortcode":"[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
		<div class="wp-block-blockstrap-blockstrap-widget-container bg-image-fixed row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"6","mb_lg":"","pt":"5","pr":"5","pl":"5","pt_lg":"4","pr_lg":"6","pb_lg":"4","pl_lg":"6","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='5'  pr='5'  pb=''  pl='5'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='4'  pr_lg='6'  pb_lg='4'  pl_lg='6'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
			<div class="wp-block-blockstrap-blockstrap-widget-container pt-5 pe-5 ps-5 pt-lg-4 pe-lg-6 pb-4 ps-lg-6 col-12 col-lg-6 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"<?php echo esc_attr( $txt_explore ); ?>","html_tag":"h1","text_color":"white","text_color_custom":"#0c0d24","font_size":"display-5","font_weight":"font-weight-bold","mr":"0"} -->
				<h1 class="wp-block-blockstrap-blockstrap-widget-heading me-0 mb-3 text-white font-weight-bold display-5"><?php echo esc_attr( $txt_explore ); ?></h1>
				<!-- /wp:blockstrap/blockstrap-widget-heading -->

				<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Discover what's happening near you, don't miss out! Book your tickets now.","html_tag":"p","mt":"3","mr":"0","mb":"4","mr_md":"0","ml_md":"0","mt_lg":"3","mr_lg":"7","mb_lg":"4"} -->
				<p class="wp-block-blockstrap-blockstrap-widget-heading mt-3 me-0 mb-4 me-md-0 ms-md-0 mt-lg-3 me-lg-7 mb-lg-4">Discover what's happening near you, don't miss out! Book your tickets now.</p>
				<!-- /wp:blockstrap/blockstrap-widget-heading -->

				<!-- wp:geodirectory/geodir-widget-search {"post_type":"gd_event","post_type_hide":true,"input_size":"lg","bar_flex_wrap":"flex-wrap","bar_flex_wrap_lg":"flex-lg-nowrap","input_border":"0","input_rounded_size":"4","btn_bg":"primary","btn_rounded_size_lg":"pill","mt":"5","mb":"","border":"0","content": "","sd_shortcode":"[gd_search post_type='gd_event'  post_type_hide='true'  hide_search_input='false'  hide_near_input='false'  input_size='lg'  bar_flex_wrap='flex-wrap'  bar_flex_wrap_md=''  bar_flex_wrap_lg='flex-lg-nowrap'  input_border='0'  input_border_opacity=''  input_rounded_size='4'  btn_bg='primary'  btn_rounded_size=''  btn_rounded_size_md=''  btn_rounded_size_lg='pill'  bg=''  mt='5'  mr=''  mb=''  ml=''  pt=''  pr=''  pb=''  pl=''  border='0'  rounded=''  rounded_size=''  rounded_size_md=''  rounded_size_lg=''  shadow=''  css_class='' ]"} -->
				<div class="wp-block-geodirectory-geodir-widget-search"></div>
				<!-- /wp:geodirectory/geodir-widget-search --></div>
			<!-- /wp:blockstrap/blockstrap-widget-container -->

			<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"6","mb_lg":"","pt":"4","pt_lg":"0","pb_lg":"0","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='4'  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg=''  pb_lg='0'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
			<div class="wp-block-blockstrap-blockstrap-widget-container pt-4 pt-lg-0 pb-0 col-12 col-lg-6 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-image {"img_src":"url","img_url":"<?php echo esc_attr( $img_url ); ?>","fallback_img_src":"default","img_alt":"Man in black suit standing on stage","img_aspect":"4by3","img_border":"0","img_rounded_size":"0","mb_lg":"0","content": "","sd_shortcode":"[bs_image img_src='url'  img_image=''  img_image_id=''  img_size=''  img_url='<?php echo esc_attr( $img_url ); ?>'  fallback_img_src='default'  fallback_img_image=''  fallback_img_image_id=''  img_alt='Man in black suit standing on stage'  img_lazyload=''  img_link_to=''  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect='4by3'  img_cover=''  img_border='0'  img_rounded=''  img_rounded_size='0'  img_shadow=''  img_overlay=''  text_color=''  font_size=''  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='0'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask=''  img_mask_position='center center'  visibility_conditions=''  css_class='' ]"} /--></div>
			<!-- /wp:blockstrap/blockstrap-widget-container --></div>
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->
