<?php
/**
 * Title: Events - Default Hero Archive
 * Slug: events-directory/hero-archive-default
 * Categories: blockstrap-hero-sections
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"rgba(0,0,0,0.65)","bg_image_use_featured":true,"pt_lg":"7","pb_lg":"6","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='rgba(0,0,0,0.65)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='true'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='7'  pr_lg=''  pb_lg='6'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 pt-7 pb-6 bg-custom-color bg-image-fixed container-fluid" style="background-color:rgba(0,0,0,0.65);background-image:url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiID8+CjxzdmcgYmFzZVByb2ZpbGU9InRpbnkiIGhlaWdodD0iNDAwIiB2ZXJzaW9uPSIxLjIiIHdpZHRoPSI0MDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6ZXY9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEveG1sLWV2ZW50cyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPjxkZWZzIC8+PHJlY3QgZmlsbD0iI2QzZDNkMyIgaGVpZ2h0PSI0MDAiIHdpZHRoPSI0MDAiIHg9IjAiIHk9IjAiIC8+PGxpbmUgc3Ryb2tlPSJ3aGl0ZSIgc3Ryb2tlLXdpZHRoPSIxMCIgeDE9IjAiIHgyPSI0MDAiIHkxPSIwIiB5Mj0iNDAwIiAvPjxsaW5lIHN0cm9rZT0id2hpdGUiIHN0cm9rZS13aWR0aD0iMTAiIHgxPSIwIiB4Mj0iNDAwIiB5MT0iNDAwIiB5Mj0iMCIgLz48cmVjdCBmaWxsPSIjZDNkM2QzIiBoZWlnaHQ9IjUwIiB3aWR0aD0iMjE4LjAiIHg9IjkxLjAiIHk9IjE3NS4wIiAvPjx0ZXh0IGZpbGw9IndoaXRlIiBmb250LXNpemU9IjMwIiBmb250LXdlaWdodD0iYm9sZCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgeD0iMjAwLjAiIHk9IjIwNy41Ij5QTEFDRUhPTERFUjwvdGV4dD48L3N2Zz4=);background-blend-mode:overlay;background-size:cover"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row"} -->
	<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 bg-image-fixed row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","flex_order":"order-1","flex_order_md":"order-md-2","css_class":"z-index\u002d\u002d2"} -->
		<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 bg-image-fixed col z-index--2 order-1 order-md-2"><!-- wp:blockstrap/blockstrap-widget-container {"text_color":"white","text_align_lg":"text-lg-center","pr":"0","pl":"0","pr_md":"3","pl_md":"3","pr_lg":"8","pl_lg":"8"} -->
			<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 pe-0 ps-0 pe-md-3 ps-md-3 pe-lg-8 ps-lg-8 bg-image-fixed text-white text-center container"><!-- wp:blockstrap/blockstrap-widget-archive-title {"prefix_hide":true,"text_color":"white","font_weight":"font-weight-bold","text_align_lg":"text-lg-center","mb_lg":"4"} /-->

				<!-- wp:term-description {"textColor":"white"} /-->

				<!-- wp:geodirectory/geodir-widget-search {"post_type":"gd_event","post_type_hide":true,"input_size":"lg","bar_flex_wrap_lg":"flex-lg-wrap-reverse","input_border":"0","btn_bg":"primary","btn_rounded_size_lg":"1","mt":"3","mb":"","border":"0","rounded":"rounded","shadow":"shadow","content": "","sd_shortcode":"[gd_search post_type='gd_event'  post_type_hide='true'  hide_search_input='false'  hide_near_input='false'  input_size='lg'  bar_flex_wrap=''  bar_flex_wrap_md=''  bar_flex_wrap_lg='flex-lg-wrap-reverse'  input_border='0'  input_border_opacity=''  input_rounded_size=''  btn_bg='primary'  btn_rounded_size=''  btn_rounded_size_md=''  btn_rounded_size_lg='1'  bg=''  mt='3'  mr=''  mb=''  ml=''  pt=''  pr=''  pb=''  pl=''  border='0'  rounded='rounded'  rounded_size=''  rounded_size_md=''  rounded_size_lg=''  shadow='shadow'  css_class='' ]"} -->
				<div class="wp-block-geodirectory-geodir-widget-search"></div>
				<!-- /wp:geodirectory/geodir-widget-search --></div>
			<!-- /wp:blockstrap/blockstrap-widget-container --></div>
		<!-- /wp:blockstrap/blockstrap-widget-container --></div>
	<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->
